"""
controller_node.py — DUT25 Coupled MPC Controller (ROS 2 Node)
==============================================================
Author:  Ian Pichs (ifp2107) — Columbia University
Course:  ELEN 6760 Discrete Control Systems, Spring 2026
Project: Evolution of Control Architectures for High-Speed Autonomous Racing

PURPOSE
-------
ROS 2 node implementing a Coupled Nonlinear MPC for lateral + longitudinal
control of the DUT25 autonomous car on the skidpad mission. This node is a
drop-in replacement for both mpc_python_exec AND longitudinal_control,
solving steering and throttle jointly via a single NLP at each timestep.

The node uses the acados solver generated by ocp_definition.py (run offline).
At startup it loads the pre-compiled C solver (build=False) so initialization
takes milliseconds, not seconds.

WHAT IS COUPLED HERE
--------------------
The Decoupled MPC (mpc_python) solves steering only, with vx fixed. This node
solves for [steer_rate, throttle] jointly, with vx as a dynamic state, under
the friction circle constraint:

    (ax / ax_max)^2 + (ay / ay_max)^2 <= 1

This forces the optimizer to trade lateral grip against longitudinal
acceleration at circle entries — the precise moment where the LQR and
Decoupled MPC rely on saturated limits rather than optimal planning.

ROS INTERFACE (identical to LQR node — drop-in replacement)
------------------------------------------------------------
Subscribes:
    /controllers/opt_requests  (controller_msgs/OptRequest)  ~40 Hz
        Reference waypoints + current vehicle state x0.
    /controllers/accel_request (controller_msgs/AccRequest)  ~250 Hz
        Speed setpoint + current speed.

Publishes:
    /controllers/opt_results   (controller_msgs/OptResult)
        N+1 = 41 predicted steer angles used by skidpad_manager for
        latency compensation (interp1d over linspace(0, 1.0, 41)).
    /controllers/long          (controller_msgs/PIDErrors)
        Throttle command: .input field read by skidpad_manager as
        the acceleration command for TrajectorySetpoints.

SOLVE LOOP (per OptRequest callback, ~40 Hz)
-------------------------------------------
1.  Extract current vehicle state x0 from msg.x0.
2.  Find nearest waypoint in the reference path.
3.  Build reference trajectory yref[k] for k=0..N from waypoints ahead.
4.  Set initial state constraint and stage references in the solver.
5.  Call solver.solve() — one SQP_RTI iteration (~1-3 ms).
6.  Extract steer sequence (41 values) and first throttle command.
7.  Publish OptResult (steer) and cache throttle for AccRequest callbacks.

WARM STARTING
-------------
The solver is warm-started from the previous solution by shifting the optimal
trajectory one step forward (x[k] <- x[k+1], u[k] <- u[k+1]) before each
solve. This keeps the initial guess close to the new optimum and ensures
RTI converges in one iteration on a smoothly evolving trajectory.
"""

# ifp2107 — all code in this file is original work by Ian Pichs (ifp2107).
# The ROS 2 interface pattern (topic names, message types, executor setup)
# mirrors the existing lqr_pid_controller/controller_node.py which is also
# authored by ifp2107. The acados solver is loaded from ocp_definition.py
# (also ifp2107). Vehicle parameters are shared DUT25 measured values.

import math
import sys

import numpy as np
import rclpy
from rclpy.node import Node

from controller_msgs.msg import AccRequest, OptRequest, OptResult, PIDErrors

# ifp2107: Import vehicle constants and solver factory from ocp_definition.
# The solver is NOT regenerated here — it loads the pre-compiled .so.
from coupled_mpc_controller.ocp_definition import (
    create_solver,
    N_HORIZON, DT, TF,
    MAX_STEER_ANGLE, MAX_STEER_RATE, MAX_THROTTLE, MAX_BRAKING,
    DRAG_COEFF, M,
    LF, LR, CF, CR,
)


# =============================================================================
# ifp2107: MODULE-LEVEL CONSTANTS
# These mirror the tunable parameters in ocp_definition.py.
# They are also exposed as ROS parameters for launch-file overrides.
# =============================================================================

VX_TARGET    = 11.25   # [m/s] skidpad cruise speed (linearization point)
LOOKAHEAD_STEPS = 5    # waypoints ahead for curvature feedforward into yref
                        # (smaller than LQR's 40 — MPC already plans ahead
                        # over the full N-step horizon; this shifts the
                        # reference origin slightly to match the MPC horizon)

# ifp2107: Warm-start mismatch threshold [m].
# If the warm-start predicted position at the mid-horizon (k=N//2) is further
# than this from the reference at that stage, the prior solution is stale and
# the warm-start is reset to neutral. This fires at the skidpad circle
# changeover where the reference path changes curvature sign — without the
# reset, the optimizer anchors to the previous circle trajectory and produces
# an extreme first-step solution (hard brake + max steer). With the reset the
# solver starts from the measured state and finds a smooth transition. The
# threshold (2.0 m) sits above normal tracking error (~0.3 m) but below the
# ~3.3 m mid-horizon mismatch at changeover.
WARM_START_MISMATCH_THRESHOLD = 3.0   # [m]


# =============================================================================
# ifp2107: HELPERS
# =============================================================================

def normalize_angle(angle: float) -> float:
    """
    ifp2107: Wrap an angle to [-pi, pi].

    PSEUDO-CODE
    -----------
    Input:  angle [rad] (any range)
    Output: angle [rad] in [-pi, pi]

    Prevents discontinuities at ±180° when computing heading error.
    """
    return (angle + math.pi) % (2.0 * math.pi) - math.pi


def compute_curvature(ref_idx: int, msg: OptRequest) -> float:
    """
    ifp2107: Estimate signed path curvature kappa = d_theta/d_s at ref_idx.

    PSEUDO-CODE
    -----------
    Input:  ref_idx — waypoint index in msg arrays
            msg     — OptRequest containing path arrays
    Output: kappa [1/m], positive = left turn, negative = right turn

    Identical implementation to lqr_pid_controller for consistency.
    Uses finite difference of heading angle divided by arc length.
    """
    n = len(msg.pos_x)
    if n < 2:
        return 0.0
    i      = min(ref_idx, n - 2)
    theta0 = math.atan2(msg.head_sin[i],     msg.head_cos[i])
    theta1 = math.atan2(msg.head_sin[i + 1], msg.head_cos[i + 1])
    ds     = math.hypot(
        msg.pos_x[i + 1] - msg.pos_x[i],
        msg.pos_y[i + 1] - msg.pos_y[i],
    )
    if ds < 1e-6:
        return 0.0
    return normalize_angle(theta1 - theta0) / ds


# =============================================================================
# ifp2107: ROS 2 NODE
# =============================================================================

class CoupledMpcController(Node):
    """
    ifp2107: ROS 2 node — Coupled MPC lateral + longitudinal controller.

    Replaces mpc_python_exec + longitudinal_control in the DUT25 skidpad
    pipeline. skidpad_manager_node requires no modification — this node
    publishes on the same topics with the same message types.

    PSEUDO-CODE (init)
    ------------------
    Input:  None (reads ROS parameters + loads acados solver)
    Output: Initialized node with solver ready, publishers/subscribers wired

    1. Declare and load ROS parameters (targets, weights, limits).
    2. Load pre-compiled acados solver (build=False — millisecond startup).
    3. Initialise warm-start buffers (previous optimal x, u trajectories).
    4. Create publishers and subscribers.
    """

    def __init__(self) -> None:
        super().__init__('coupled_mpc_controller')

        # ------------------------------------------------------------------
        # ifp2107: ROS parameters — expose key tuning knobs for launch-file
        # override without recompiling. Defaults match ocp_definition.py.
        # ------------------------------------------------------------------
        self.declare_parameter('vx_target',      VX_TARGET)
        self.declare_parameter('lookahead_steps', LOOKAHEAD_STEPS)
        self.declare_parameter('max_steer_angle', MAX_STEER_ANGLE)
        self.declare_parameter('max_steer_rate',  MAX_STEER_RATE)
        self.declare_parameter('max_throttle',    MAX_THROTTLE)
        self.declare_parameter('max_braking',     MAX_BRAKING)

        p = lambda name: self.get_parameter(name).value
        self._vx_target       = float(p('vx_target'))
        self._lookahead       = int(p('lookahead_steps'))
        self._max_steer       = float(p('max_steer_angle'))
        self._max_steer_rate  = float(p('max_steer_rate'))
        self._max_throttle    = float(p('max_throttle'))
        self._max_braking     = float(p('max_braking'))

        # ------------------------------------------------------------------
        # ifp2107: Load acados solver.
        # build=False: loads the pre-compiled .so generated by ocp_definition.py.
        # This must be run AFTER ocp_definition.py has been executed once.
        # ------------------------------------------------------------------
        self.get_logger().info('Loading Coupled MPC acados solver...')
        try:
            self._solver = create_solver(build=False)
        except Exception as e:
            self.get_logger().error(
                f'Failed to load acados solver: {e}\n'
                f'Run ocp_definition.py inside the Docker container first.'
            )
            raise

        self._nx = 7   # state dimension
        self._nu = 2   # control dimension
        self._ny = self._nx + self._nu   # output dimension = 9

        # ------------------------------------------------------------------
        # ifp2107: Warm-start buffers.
        # Stores the previous optimal state and control trajectories so the
        # next solve is initialised close to the optimum (RTI requirement).
        # Initialised to straight-line cruise at target speed.
        # ------------------------------------------------------------------
        self._prev_x = np.zeros((N_HORIZON + 1, self._nx))
        self._prev_u = np.zeros((N_HORIZON,     self._nu))
        for k in range(N_HORIZON + 1):
            self._prev_x[k, 6] = self._vx_target   # vx = cruise speed
        # Throttle warm start: drag compensation at cruise speed
        u_th_cruise = DRAG_COEFF * self._vx_target**2
        for k in range(N_HORIZON):
            self._prev_u[k, 1] = u_th_cruise

        # ------------------------------------------------------------------
        # ifp2107: State cache — vx updated by AccRequest at 250 Hz.
        # Used to complete x0 (OptRequest gives vy, r, steer, pos, heading
        # but not vx — vx comes from AccRequest.current_speed).
        # ------------------------------------------------------------------
        self._current_vx: float = self._vx_target
        self._last_throttle: float = DRAG_COEFF * self._vx_target**2

        # ifp2107: Flag for seeding warm-start from the first real x0.
        # The zero-position warm-start is invalid until the vehicle state
        # is known; on the first OptRequest we overwrite all stages with x0.
        self._warm_start_seeded: bool = False

        # ------------------------------------------------------------------
        # ifp2107: Publishers
        # ------------------------------------------------------------------
        self._opt_result_pub = self.create_publisher(
            OptResult, '/controllers/opt_results', 1
        )
        self._long_pub = self.create_publisher(
            PIDErrors, '/controllers/long', 1
        )

        # ifp2107: Subscribers — queue depth 1: always process the latest
        # message; discard stale ones (same policy as LQR node).
        self.create_subscription(
            OptRequest, '/controllers/opt_requests',
            self._on_opt_request, 1
        )
        self.create_subscription(
            AccRequest, '/controllers/accel_request',
            self._on_acc_request, 1
        )

        self.get_logger().info(
            f'Coupled MPC controller initialised.\n'
            f'  N={N_HORIZON}, dt={DT}s, Tf={TF}s\n'
            f'  vx_target={self._vx_target} m/s\n'
            f'  solver: SQP_RTI + ERK4'
        )

    # =========================================================================
    # ifp2107: LATERAL — OptRequest callback (~40 Hz)
    # =========================================================================

    def _on_opt_request(self, msg: OptRequest) -> None:
        """
        ifp2107: Main MPC solve triggered by each OptRequest from skidpad_manager.

        PSEUDO-CODE
        -----------
        Input:  OptRequest msg — reference path (N+1 waypoints) + state x0
        Output: Publishes OptResult (41-element steer sequence) and caches
                throttle for the next AccRequest publication.

        Steps:
          1. Extract current vehicle state x0 (including cached vx).
          2. Find nearest waypoint; build per-stage reference yref[k].
          3. Shift warm-start buffers one step forward (RTI warm-start).
          4. Set initial state + warm-start in solver.
          5. Call solver.solve() — one SQP_RTI iteration.
          6. Extract steer sequence (N+1) and throttle from solution.
          7. Publish OptResult; cache throttle for AccRequest.
        """
        if len(msg.pos_x) == 0:
            self.get_logger().warning(
                'Received OptRequest with empty path — skipping.',
                throttle_duration_sec=2.0,
            )
            return

        x0_msg = msg.x0

        # ------------------------------------------------------------------
        # ifp2107: Step 1 — assemble 7-element state vector from x0 message
        # and cached vx (vx comes from AccRequest, not OptRequest).
        # x = [pos_x, pos_y, psi, vy, r, steer, vx]
        # ------------------------------------------------------------------
        x0 = np.array([
            x0_msg.pos_x,
            x0_msg.pos_y,
            x0_msg.heading,
            x0_msg.vy,
            x0_msg.r,
            x0_msg.steer,
            self._current_vx,
        ], dtype=float)

        # ------------------------------------------------------------------
        # ifp2107: Step 2 — build per-stage reference trajectory.
        # For each stage k, the reference is the waypoint at (ref_idx + k)
        # steps ahead, clamped to the end of the path array.
        # Feedforward references (r_ref, vy_ref, steer_ref) use path
        # curvature at that waypoint — same formula as LQR feedforward.
        # ------------------------------------------------------------------
        # ifp2107: Seed warm-start from actual x0 on first call.
        # Default init is all-zeros except vx, which is a poor starting point
        # when the vehicle is already moving on track. Seeding all horizon
        # stages with the measured state gives ERK4 a consistent starting
        # trajectory and avoids large Jacobian errors on the first solve.
        if not self._warm_start_seeded:
            for k in range(N_HORIZON + 1):
                self._prev_x[k] = x0.copy()
            self._warm_start_seeded = True

        ref_idx = self._nearest_waypoint(x0_msg.pos_x, x0_msg.pos_y, msg)
        n_wp    = len(msg.pos_x)

        # ifp2107: Capture reference position and steer at mid-horizon.
        # Used by the warm-start mismatch guard to (a) detect the changeover
        # and (b) seed the steer-rate warm-start in the correct direction.
        px_ref_mid:    float = 0.0
        py_ref_mid:    float = 0.0
        steer_ref_mid: float = 0.0

        for k in range(N_HORIZON + 1):
            # ifp2107: Waypoint index for this stage.
            # No additional lookahead offset — the MPC horizon already provides
            # N-step lookahead. Adding a manual offset shifts ALL stage references
            # forward, creating a systematic position bias where the MPC tries to
            # be k+offset steps ahead at stage k instead of k steps ahead.
            wp_k = min(ref_idx + k, n_wp - 1)

            # Reference pose at stage k
            px_ref  = msg.pos_x[wp_k]
            py_ref  = msg.pos_y[wp_k]
            psi_ref = math.atan2(msg.head_sin[wp_k], msg.head_cos[wp_k])

            if k == N_HORIZON // 2:
                px_ref_mid    = px_ref
                py_ref_mid    = py_ref
                steer_ref_mid = steer_ref

            # ifp2107: Curvature-based feedforward references.
            # Identical to LQR: shifts vy, r, steer references to the
            # steady-state values for the upcoming curvature.
            kappa     = compute_curvature(wp_k, msg)
            vx_cur    = self._current_vx
            r_ref     = vx_cur * kappa
            steer_ref = -(LF + LR) * kappa
            vy_ref    = 0.2429 * vx_cur * r_ref

            # Reference speed: target cruise speed
            vx_ref = self._vx_target

            # ifp2107: Throttle reference = drag compensation at cruise speed.
            # This biases the solver toward maintaining speed rather than
            # accelerating or braking unnecessarily on straight sections.
            u_th_ref = DRAG_COEFF * vx_ref**2

            # Assemble yref for this stage
            # y = [pos_x, pos_y, psi, vy, r, steer, vx, steer_rate, throttle]
            if k < N_HORIZON:
                yref_k = np.array([
                    px_ref, py_ref, psi_ref,
                    vy_ref, r_ref, steer_ref, vx_ref,
                    0.0,         # steer_rate reference = 0 (smooth actuation)
                    u_th_ref,    # throttle reference = drag compensation
                ], dtype=float)
                self._solver.set(k, 'yref', yref_k)
            else:
                # Terminal stage: states only (no control reference)
                yref_e = np.array([
                    px_ref, py_ref, psi_ref,
                    vy_ref, r_ref, steer_ref, vx_ref,
                ], dtype=float)
                self._solver.set(k, 'yref', yref_e)

        # ------------------------------------------------------------------
        # ifp2107: Step 3 — warm-start: shift previous solution one step.
        # x_warm[k] = x_prev[k+1] for k=0..N-1; repeat last state at N.
        # u_warm[k] = u_prev[k+1] for k=0..N-2; repeat last control at N-1.
        # This gives the solver a high-quality starting point for RTI.
        # ------------------------------------------------------------------
        x_warm = np.vstack([self._prev_x[1:], self._prev_x[-1:]])
        u_warm = np.vstack([self._prev_u[1:], self._prev_u[-1:]])

        # ifp2107: Warm-start mismatch guard.
        # Compare the warm-start predicted position at k=N//2 against the
        # reference at that stage. A large error means the prior solution is
        # pointing in the wrong direction (e.g., at the skidpad changeover the
        # previous trajectory curves into the old circle while the reference now
        # curves into the new one). Reset to neutral — x0 everywhere, cruise
        # throttle — so SQP_RTI solves from a clean starting point rather than
        # anchoring to a stale trajectory and producing extreme controls.
        k_mid = N_HORIZON // 2
        ws_err = math.hypot(
            float(x_warm[k_mid][0]) - px_ref_mid,
            float(x_warm[k_mid][1]) - py_ref_mid,
        )
        if ws_err > WARM_START_MISMATCH_THRESHOLD:
            u_th_cruise = DRAG_COEFF * self._vx_target**2
            self.get_logger().warning(
                f'Warm-start reset: mismatch {ws_err:.2f}m at k={k_mid} — '
                f'stale prior cleared, seeding from x0.',
            )
            for k in range(N_HORIZON + 1):
                self._prev_x[k] = x0.copy()
            for k in range(N_HORIZON):
                self._prev_u[k] = np.array([0.0, u_th_cruise])
            x_warm = np.vstack([self._prev_x[1:], self._prev_x[-1:]])
            u_warm = np.vstack([self._prev_u[1:], self._prev_u[-1:]])

        for k in range(N_HORIZON + 1):
            self._solver.set(k, 'x', x_warm[k])
            if k < N_HORIZON:
                self._solver.set(k, 'u', u_warm[k])

        # ------------------------------------------------------------------
        # ifp2107: Step 4 — set initial state constraint (hard equality).
        # Pins x[0] = x0 (the current measured state).
        # ------------------------------------------------------------------
        self._solver.set(0, 'lbx', x0)
        self._solver.set(0, 'ubx', x0)

        # ------------------------------------------------------------------
        # ifp2107: Step 5 — solve (one SQP_RTI iteration).
        # Status 0 = solved to tolerance; non-zero = not fully converged
        # (still usable with RTI — the solution is iteratively improving).
        # ------------------------------------------------------------------
        status = self._solver.solve()

        # ifp2107: Status interpretation for SQP_RTI:
        # 0 = converged, 2 = max-iter (shouldn't happen with RTI's single step),
        # 3 = min-step, 4 = QP solver failure.
        # On status 3/4 acados returns the warm-start values (previous solution
        # shifted one step) — these are physically valid and usable.
        # Status 1 = NaN detected; solution is unsafe and must be discarded.
        if status == 1:
            self.get_logger().warning(
                'Coupled MPC: NaN detected in solution — holding previous command.',
                throttle_duration_sec=1.0,
            )
        elif status not in (0, 2):
            self.get_logger().warning(
                f'Coupled MPC solver status={status} (QP/min-step) — '
                f'using warm-start values.',
                throttle_duration_sec=1.0,
            )

        # ------------------------------------------------------------------
        # ifp2107: Step 6 — extract optimal solution.
        # Steer sequence: x[k][5] (steer state) for k=0..N gives N+1=41 values.
        # Throttle: u[0][1] — first optimal throttle command.
        # Update warm-start buffers for next solve.
        # ------------------------------------------------------------------
        # ifp2107: Extract solution with NaN guard.
        # On status 1 (NaN), solver values are unsafe — fall back to the
        # shifted warm-start (prev_x already shifted above). On status 3/4
        # (QP fail), acados returns warm-start values directly; we accept them.
        steer_seq = []
        for k in range(N_HORIZON + 1):
            x_k = self._solver.get(k, 'x')
            steer_val = float(x_k[5])
            if math.isnan(steer_val) or math.isinf(steer_val):
                # Fall back to the already-shifted warm-start value
                steer_val = float(np.clip(x_warm[k][5], -self._max_steer, self._max_steer))
            else:
                steer_val = float(np.clip(steer_val, -self._max_steer, self._max_steer))
                self._prev_x[k] = x_k   # only update warm-start with valid values
            steer_seq.append(steer_val)

        for k in range(N_HORIZON):
            u_k = self._solver.get(k, 'u')
            if not (math.isnan(float(u_k[0])) or math.isnan(float(u_k[1]))):
                self._prev_u[k] = u_k

        u0 = self._solver.get(0, 'u')
        throttle_val = float(u0[1])
        if math.isnan(throttle_val) or math.isinf(throttle_val):
            throttle_val = float(self._last_throttle)   # hold previous command
        self._last_throttle = float(np.clip(throttle_val, -self._max_braking, self._max_throttle))

        # ------------------------------------------------------------------
        # ifp2107: Step 7 — publish OptResult.
        # steer: 41-element sequence for skidpad_manager latency compensation.
        # Other trajectory fields populated from solver state predictions
        # for Foxglove visualization (same format as LQR OptResult).
        # ------------------------------------------------------------------
        result            = OptResult()
        result.header     = msg.header
        result.steer      = steer_seq

        # Populate trajectory from solver predictions
        pos_x_pred, pos_y_pred, heading_pred = [], [], []
        vy_pred, r_pred, steer_rate_pred     = [], [], []
        for k in range(N_HORIZON + 1):
            x_k = self._solver.get(k, 'x')
            pos_x_pred.append(float(x_k[0]))
            pos_y_pred.append(float(x_k[1]))
            heading_pred.append(float(x_k[2]))
            vy_pred.append(float(x_k[3]))
            r_pred.append(float(x_k[4]))

        result.pos_x   = pos_x_pred
        result.pos_y   = pos_y_pred
        result.heading = heading_pred
        result.vy      = vy_pred
        result.r       = r_pred
        result.steering_rate = [float(self._solver.get(k, 'u')[0])
                                 if k < N_HORIZON else 0.0
                                 for k in range(N_HORIZON + 1)]
        # ifp2107: Report FAILURE only on NaN (status 1 — unsafe values).
        # QP fail (3/4) returns warm-start values which are physically valid;
        # reporting SUCCESS lets the manager always update its control buffer.
        result.solver_status = OptResult.FAILURE if status == 1 else OptResult.SUCCESS

        self._opt_result_pub.publish(result)

        self.get_logger().info(
            f'MPCC | status={status}  '
            f'steer[0]={steer_seq[0]:+.3f}rad  '
            f'throttle={self._last_throttle:+.3f}  '
            f'vx={x0[6]:.2f}m/s',
            throttle_duration_sec=0.25,
        )

    # =========================================================================
    # ifp2107: LONGITUDINAL — AccRequest callback (~250 Hz)
    # =========================================================================

    def _on_acc_request(self, msg: AccRequest) -> None:
        """
        ifp2107: Publish the throttle from the last MPC solve via PIDErrors.

        PSEUDO-CODE
        -----------
        Input:  AccRequest msg — current_speed, desired_speed, braking flag
        Output: Publishes PIDErrors with .input = MPC throttle command

        The Coupled MPC computes throttle jointly with steering at 40 Hz
        (OptRequest rate). This callback runs at 250 Hz and re-publishes the
        cached throttle from the last solve between MPC updates. If the
        braking flag is set by skidpad_manager, hard braking overrides MPC.

        skidpad_manager reads PIDErrors.input as the acceleration/throttle
        value for TrajectorySetpoints — same field as the LQR PID output.
        """
        # ifp2107: Update cached vx for use in next MPC solve.
        self._current_vx = float(max(msg.current_speed, 0.5))

        throttle = -20.0 if msg.braking else self._last_throttle

        pid_msg            = PIDErrors()
        pid_msg.ref        = float(msg.desired_speed)
        pid_msg.current    = float(msg.current_speed)
        pid_msg.error      = float(msg.desired_speed - msg.current_speed)
        pid_msg.integral   = 0.0    # MPC has no integrator state to report
        pid_msg.derivative = 0.0
        pid_msg.input      = throttle
        self._long_pub.publish(pid_msg)

    # =========================================================================
    # ifp2107: HELPERS
    # =========================================================================

    def _nearest_waypoint(self, px: float, py: float,
                           msg: OptRequest) -> int:
        """
        ifp2107: Return index of the waypoint closest to (px, py).

        PSEUDO-CODE
        -----------
        Input:  px, py — current vehicle position [m]
                msg    — OptRequest with pos_x, pos_y waypoint arrays
        Output: integer index into msg arrays

        Uses vectorised numpy hypot for speed (called at 40 Hz).
        Identical to lqr_pid_controller implementation.
        """
        xs = np.array(msg.pos_x)
        ys = np.array(msg.pos_y)
        return int(np.argmin(np.hypot(xs - px, ys - py)))


# =============================================================================
# ifp2107: ENTRY POINT
# =============================================================================

def main(args=None) -> None:
    rclpy.init(args=args)
    node = CoupledMpcController()
    executor = rclpy.executors.MultiThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
